apiVersion: v1
kind: Service
metadata:
  name: enrichment
  labels:
    {{- include "deps-enrichment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.enrichment.service.type }}
  ports:
    - port: {{ .Values.enrichment.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "deps-enrichment.selectorLabels" . | nindent 4 }}
